# Primary targets

barber: JavaFiles

# Executable targets
JavaFiles: SleepingBarbers.java
	javac SleepingBarbers.java

# Add a clean target that silently removes the .o files
clean:
	@rm *.o *.class 2> /dev/null || true
