# Primary targets

barber: JavaFiles

# Executable targets
JavaFiles: Barbers.java
	javac Barbers.java

# Add a clean target that silently removes the .o files
clean:
	@rm *.o *.class 2> /dev/null || true
